//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takochu.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PropertyGrid_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyGrid_EN() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Takochu.Properties.PropertyGrid_EN", typeof(PropertyGrid_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ObjectName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ObjectName {
            get {
                return ResourceManager.GetString("ObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Renaming an object に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ObjectNameDes {
            get {
                return ResourceManager.GetString("ObjectNameDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string pos_x {
            get {
                return ResourceManager.GetString("pos_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sets the position of the X coordinate.
        ///It is affected by the rotation and position of the zone. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string pos_xDes {
            get {
                return ResourceManager.GetString("pos_xDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string pos_y {
            get {
                return ResourceManager.GetString("pos_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sets the position of the Y coordinate.
        ///It is affected by the rotation and position of the zone. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string pos_yDes {
            get {
                return ResourceManager.GetString("pos_yDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string pos_z {
            get {
                return ResourceManager.GetString("pos_z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sets the position of the Z coordinate.
        ///It is affected by the rotation and position of the zone. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string pos_zDes {
            get {
                return ResourceManager.GetString("pos_zDes", resourceCulture);
            }
        }
    }
}
